name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v2
        with:
         repository: andycockerill-cpi/congenial-sniffle
         token: ${{ secrets.GH_ACCESS_TOKEN }}
         path: ec2-actions-runner

      - name: Start EC2 runner
        id: start-runner
        uses: andycockerill-cpi/congenial-sniffle/start@v0.0.11
        with:
          aws-region: us-west-2
          ami: ami-05c3ef1e5b4953093
          instance_types: '["t2.medium", "t2.micro", "t2.small"]'
          vpc-security-group-ids: '["sg-04bbd3c02eadb42d5"]'
          subnets:  '["subnet-043d3e6e6af5cf5dd", "subnet-0b8eb2718059ffa6f", "subnet-0d3ff0362c8fab2ba"]'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          aws-launch-template: lt-05fce14cda84fcee9
    outputs:
      instance-id: ${{ steps.start-runner.outputs.instance-id }}

  main:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.instance-id }}
    steps:
      - run: uname -a

  stop-runner:
    if: always()
    needs: [start-runner, main]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v2
      with:
        repository: andycockerill-cpi/congenial-sniffle
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        path: ec2-actions-runner
    - name: Stop runner
      uses: andycockerill-cpi/congenial-sniffle/stop@v0.0.11
      with:
        aws-region: us-west-2
        instance-id: ${{ needs.start-runner.outputs.instance-id }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-launch-template: lt-05fce14cda84fcee9